### ISSUE TITLE
Uncaught TypeError after submitting address

### ISSUE THREAD

**Issue by ald1897** [campaignzero/campaign-zero-widget#19]
#### Overview:

After entering an address or zip code, widget spits out an uncaught typeError in chrome dev console. 
Firefox reports a request timeout error as well. Did not test in other browsers

#### Acceptance Criteria:

_( issue will not be considered complete unless this list of criteria is met, e.g. intended usage, expected functionality, specific metrics met, etc. )_

#### Steps to Duplicate _( required for bug reports )_:

Enter zip code
Submit
F12
TypeError reported:
Uncaught TypeError: Cannot read property 'results' of null
    at Object.success (app.js?v=1.5.0:90)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at y (jquery.min.js:4)
    at XMLHttpRequest.c (jquery.min.js:4)
success @ app.js?v=1.5.0:90
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
y @ jquery.min.js:4
c @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
getRepresentatives @ app.js?v=1.5.0:82
success @ app.js?v=1.5.0:734
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
y @ jquery.min.js:4
c @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
geoCodeAddress @ app.js?v=1.5.0:703
(anonymous) @ app.js?v=1.5.0:914
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3

#### System Info _( required for bug reports )_:

Windows 10 | Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)

#### Relevant Documentation _( optional )_

![c0error](https://user-images.githubusercontent.com/21186193/83527105-575d7580-a4b5-11ea-9485-de8f96fe1a67.JPG)

**Comment by manifestinteractive** [comment]
Thanks for report this.  This was actually an issue with OpenStates.org rejecting our API Key since we had exceeded our threshold, which was more than double what we normally use in a day.  They have been gracious enough to remove the cap that was placed on our API Key, and we are now fully back in business.
