### ISSUE TITLE
link to github repo on the site somewhere?

### ISSUE THREAD

**Issue by codersquid** [campaignzero/campaign-zero-widget#4]
Hi, I learned about this repo via a tweet. Maybe add a link to github on your site for people who would be interested in watching the repo and helping.

**Comment by latazzajones** [comment]
@codersquid It looks like it linked under the widget on the [joincampaignzero](http://www.joincampaignzero.org/#action) site so that people know they can use it - which is not quite the same as an invite to contribute but it's linked none-the-less.

**Comment by codersquid** [comment]
Oh, I missed that link. My mistake. Apologies.
